---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: dev

inputs:
- name: resource-src

outputs:
- name: build-artifacts

run:
  path: resource-src/ci/tasks/build-artifacts

params:
  DOCKERFILE_DIR: "resource-src/docker-prod/"
