---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: dev

inputs:
- name: resource-src
- name: terraform-github-release

outputs:
- name: updated-resource-src

run:
  path: resource-src/ci/tasks/bump-terraform-cli
