---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: dev

inputs:
- name: resource-src

run:
  path: resource-src/scripts/run-tests

params:
  AWS_ACCESS_KEY:           ""
  AWS_SECRET_KEY:           ""
  AWS_BUCKET:               ""
  AWS_BUCKET_SUBFOLDER:     ""
  S3_COMPATIBLE_BUCKET:     ""
  S3_COMPATIBLE_ENDPOINT:   ""
  S3_COMPATIBLE_ACCESS_KEY: ""
  S3_COMPATIBLE_SECRET_KEY: ""
  S3_KMS_KEY_ID:            ""
